use_frameworks!

platform :ios, '10.0'

target 'Fiserv_QR_SDK_Example' do
  pod 'Fiserv_QR_SDK', :path => '../'

  target 'Fiserv_QR_SDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
