use_frameworks!

platform :ios, '13.0'

target 'Fiserv_QR_SDK_Example' do
  pod 'Fiserv_QR_SDK', :path => '../'

  target 'Fiserv_QR_SDK_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 10.0.0'
  end
  
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
